### ISSUE TITLE
Server log gridview script

### ISSUE THREAD

**Issue by mattsw** [brianary/scripts#1]
I would like to see a generic import of a server log script which can fetch and ogv server logs :)

**Requested:**
1. Ability to gather server logs VIA Alias **OR** Fully Qualified Domain Name and output them via grid view.

**Comment by brianary** [comment]
Aliases are supported for Get-AspNetEvents.ps1 , for grid view, just pipe
to ogv.

**Comment by mattsw** [comment]
Seems reasonable enough to me. I appreciate the follow up :)

**Comment by brianary** [comment]
No problem, thanks for your interest.
